#!/bin/bash

if [ -z "$1" ]
    then
        echo "Usage: ./deploy "commit message""
        exit 1
fi
 
bundle exec rake generate && bundle exec rake deploy && git commit -a -m "$1" && git push origin source
